void setup() {
  AFMS.begin();
  SPEED_CONTROL_INITILIAZE ();
  APP_COMMUNICATION_INITIALIZE();  
  APP_LEFT_MOTOR_INITIALIZE();
  APP_RIGHT_MOTOR_INITIALIZE();
}

void loop() {
  APP_LEFT_MOTOR_TASKS();
  APP_RIGHT_MOTOR_TASKS();
}
